baseURL = "https://mirror.bit.edu.cn/"
languageCode = "zh-CN"
title = "北京理工大学 开源软件镜像服务"
theme = "bitnp-mirror"
disableKinds=["sitemap"]
hasCJKLanguage = true

[params]
briefTitle = "北理工开源软件镜像"
feedbackLink = "https://github.com/bitnp/issues/"
newMirrorLink = "https://github.com/BITNP/issues/issues/new?labels=enhancement%2C+mirror.bitnp.net&template=-mirror-repo---------.md&title=[mirror%2Frepo]"
gitLink = "https://github.com/bitnp/bitnp-mirrors-web/"
statusJSON = "/status/jobs.json"

[permalinks]
help = "/help/:filename/"
news = "/news/:filename/"

[taxonomies]
category = "categories" # only for mirror

[menu]
[[menu.main]]
identifier = "help"
name = "帮助文档"
title = ""
url = "/help/"
weight = 10

[[menu.main]]
identifier = "status"
name = "服务状态"
title = ""
url = "/status/"
weight = 20
